baseurl = "https://cromleylabs.com"
title = "Lars Cromley"
theme = "puppet"
copyright = "&copy; <a href=\"https://github.com/callmeradical\">Lars Cromley</a> 2017"
disqusShortname = "callmeradical"
googleAnalytics = "UA-159931755-2"
languageCode = "en"
defaultContentLanguage = "en"

hasCJKLanguage = true
enableInlineShortcodes = true
enableEmoji = true
# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]

Paginate = 4 

[outputs]
home = ["HTML", "JSON", "RSS"]

# prevent build failures when using Hugo's template _internal/opengraph.html 
[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[markup]
[markup.highlight]
noClasses = true
codeFences = true
guessSyntax = true
lineNos = true
lineNumbersInTable = false
style = "dracula"

[markup.goldmark.renderer]
unsafe = true

[menu]
[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = -150
[[menu.main]]
identifier = "archive"
name = "Archive"
url = "/archive/"
weight = 10
[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = -100

[params]
author = "Lars Cromley"
description = ""
keywords = "blog,personal"
img_home = "img/truck-bg.jpeg"
img_404 = "img/404-bg.jpg"
useFaviconGenerator = true
custom_js = []
custom_css = [] # ["css/custom.css"]  Add your file to assets folder  [assets/css/custom.css]

[params.sidebar]
enable = true
gravatarEmail = "lars@cromleylabs.com"
# Overwritten by your gravatar image if `gravatarEmail` is filled
bio = "assorted esoterica"

[params.social]
medium = "larscromley"
linkedin = "larscromley"
github = "callmeradical"
twitter = "larscromley"
rss = true


# See https://giscus.app/
[params.giscus]
enable = true
repo = "roninro/hugo-theme-puppet"
repo_id = "R_kgDOHuvyhw"
category = "General"
category_id = "DIC_kwDOHuvyh84CQjDo"
input_position = "top"
theme = "light_tritanopia"
lang = "en"
